# Generated by Django 2.1.4 on 2019-01-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fupload',
            name='up_file',
            field=models.FileField(default='background.jpg', upload_to=''),
        ),
    ]
